@if($charge->type ==0)
    @switch($charge->charge_type)
        @case(1)
        <span>支付宝</span>
        @break
        @case(2)
        <span>微信</span>
        @break
    @endswitch
@elseif($charge->type ==1)
    @switch($charge->charge_type)
        @case(1)
        <span>中国建设银行</span>
        @break
        @case(2)
        <span>中国工商银行</span>
        @break
        @case(3)
        <span>中国农业银行</span>
        @break
        @case(4)
        <span>中国银行</span>
        @break
        @case(5)
        <span>中国邮政储蓄银行</span>
        @break
        @case(6)
        <span>招商银行</span>
        @break
        @case(7)
        <span>平安银行</span>
        @break
        @case(8)
        <span>民生银行</span>
        @break
        @case(9)
        <span>交通银行</span>
        @break
        @case(10)
        <span>光大银行</span>
        @break
        @case(11)
        <span>中信银行</span>
        @break
        @case(12)
        <span>广发银行</span>
        @break
        @case(13)
        <span>兴业银行</span>
        @break
        @case(14)
        <span>上海浦东发展银行</span>
        @break
        @case(49)
        <span>其他银行</span>
        @break
    @endswitch
@endif